force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>An object whose every instance is a meeting</description>
    <label>Meeting</label>
    <nameField>
        <label>Meeting__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field of the account ID that created the meeting.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MeetingTriggerHandler.cls
public class MeetingTriggerHandler {

    /**
     * @Method Name: populateAccount
     * @input meetings - List of Meeting__c records from Trigger
     * @Description: Placeholder function. Account__c is now filled by LWC automatically.
     *              Can be used for default Account assignment if needed.
     * @Created by Elon Yifrah
     * @Created Date: 2025-12-01
     */
    public static void populateAccount(List<Meeting__c> meetings) {
        // No action needed, LWC fills Account__c
    }
}